package xyz.angm.lox

/** This file is autogenerated using [xyz.angm.lox.tool.defineAst]. DO NOT EDIT DIRECTLY! */
abstract class Statement {

    abstract fun <R> accept(visitor: Visitor<R>): R

    interface Visitor<R> {
        fun visitExpressionStatement(statement: Expression): R
        fun visitPrintStatement(statement: Print): R
        fun visitVarStatement(statement: Var): R
    }

    class Expression(
        val expression: xyz.angm.lox.Expression
    ) : Statement() {
        override fun <R> accept(visitor: Visitor<R>) = visitor.visitExpressionStatement(this)
    }

    class Print(
        val expression: xyz.angm.lox.Expression
    ) : Statement() {
        override fun <R> accept(visitor: Visitor<R>) = visitor.visitPrintStatement(this)
    }

    class Var(
        val name: Token,
        val initializer: xyz.angm.lox.Expression?
    ) : Statement() {
        override fun <R> accept(visitor: Visitor<R>) = visitor.visitVarStatement(this)
    }

}
